#modify the value of the weights for the state B to 0.5. plot the evolution of the population for 15 steps based on sequence S. does the population survive after 15th steps? write a report which must contain the report for these 15 steps and the answer to the question.
import numpy as np
import matplotlib.pyplot as plt

states = ['A', 'B', 'C']
trans_matrix = {
    'A': [0.0, 0.4, 0.6],
    'B': [0.5, 0.5, 0.0],
    'C': [0.2, 0.2, 0.6]
}
weights = {'A': 1.5, 'B': 0.5, 'C': 3.3}

s = ['A']
for _ in range(15):
    p = trans_matrix[s[-1]]
    next_s = np.random.choice(states, p=p)
    s.append(next_s)

population = [0.5]
for i in range(15):
    r = weights[s[i]]
    x_next = r * population[-1] * (1 - population[-1])
    population.append(x_next)

plt.plot(population, '-o', label='Population Size')
plt.xlabel('Step')
plt.ylabel('Value')
plt.legend()
plt.show()

print("Sequence S:", s)
print("Population values:", population)

#report :
#The Markov machine was run for 15 steps starting from state A. The growth factor ($r$) for each step was determined by the weight of the current state. The weight for state B was modified to $0.5$ as requested.
#The sequence of states generated by the transition probabilities:
#S = [A, B, A, C, C, A, C, A, B, A, C, B, A, B, B, A] 
#The population started at 0.5. In the steps where state B was active (r=0.5), the population underwent a significant contraction because the growth factor was below the survival threshold (r < 1). Steps with state C (r=3.3) saw more chaotic fluctuations, while state A (r=1.5) provided moderate growth.
#Step 0: 0.500000
#Step 1: 0.375000
#Step 2: 0.117188
#Step 3: 0.155182
#Step 4: 0.432632
#Step 5: 0.810023
#Step 6: 0.230829
#Step 7: 0.585904
#Step 8: 0.363931
#Step 9: 0.115743
#Step 10: 0.153519
#Step 11: 0.428839
#Step 12: 0.122468
#Step 13: 0.161204
#Step 14: 0.067609
#Step 15: 0.031519
#After the 15th step, the population size is approximately 0.0315. Although the population has significantly decreased compared to its starting value (largely due to the low weight of state B), it has not reached zero. Therefore, the population technically survives after 15 steps, though it is in a precarious state. If the system continues to trigger state B frequently, the population will continue to approach zero asymptotically.